{
 "title": "Mungos",
 "time": { "from": "2026-03-21T07:06:41.762Z", "to": "2026-03-21T10:23:31.286Z" },
 "templating": {
  "list": [
   {
    "name": "sniffer",
    "query": {
     "query": "label_values(sniffer_well_known_ports,sniffer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Распределение по портам",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "repeat": "sniffer",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sniffer_well_known_ports{sniffer=\"$sniffer\"}"
    }
   ]
  },
  {
   "title": "Известные пакеты (5 сек)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sniffer_known_packets_5sec", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Неизвестные пакеты (5 сек)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sniffer_unknown_packets_5sec", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Скорость пакетов (пакет/сек)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sniffer_packets_per_second", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "SYN пакеты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "sniffer_tcp_syn_packets", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Топ сервисов по пакетам",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sniffer_top_services", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Топ сервисов по соединениям",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sniffer_top_services_connections",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RST пакеты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "sniffer_tcp_rst_packets", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Активные TCP соединения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "sniffer_tcp_connections", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "FIN пакеты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "sniffer_tcp_fin_packets", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Package total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "expr": "sniffer_packets_total", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}