name: mungos-sniffer

services:
  clickhouse-sniffer:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: mungos-clickhouse-sniffer
    restart: unless-stopped
    environment:
      CLICKHOUSE_DB: ${SNIFFER_DB_NAME}
      CLICKHOUSE_USER: ${SNIFFER_DB_USER}
      CLICKHOUSE_PASSWORD: ${SNIFFER_DB_PASS}
    volumes:
      - clickhouse-sniffer-data:/var/lib/clickhouse
    expose:
      - "8123"
      - "9000"
    networks:
      - sniffer-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  sniffer-app:
    build:
      context: ../sniffer
      dockerfile: Dockerfile
    container_name: mungos-sniffer
    depends_on:
      clickhouse-sniffer:
        condition: service_started
    restart: unless-stopped
    environment:
        DB_TYPE: ${DB_TYPE}
        DB_HOST: ${SNIFFER_DB_HOST}
        DB_PORT: ${SNIFFER_DB_PORT}
        DB_USER: ${SNIFFER_DB_USER}
        DB_PASS: ${SNIFFER_DB_PASS}
        DB_NAME: ${SNIFFER_DB_NAME}
        DB_PROTOCOL: ${SNIFFER_DB_PROTOCOL}
        TZ: ${TZ}
        SNIFFER_DEVICE: ${SNIFFER_DEVICE}
        SNIFFER_PROMISC: ${SNIFFER_PROMISC}
        SNIFFER_FILTER: ${SNIFFER_FILTER}
        SNIFFER_LOG: ${SNIFFER_LOG}
        SNIFFER_ID: ${SNIFFER_ID}
        SNIFFER_GRPC_PORT: ${SNIFFER_GRPC_PORT}
        DEFAULT_MASTER_KEY: ${DEFAULT_MASTER_KEY}
    ports:
      - "${SNIFFER_GRPC_PORT}:3331" 
      - "0.0.0.0:${SNIFFER_GRPC_PORT}:3331"
    networks:
      sniffer-network:
      mungos-shared:
        ipv4_address: 172.20.0.10
    develop:
      watch:
        - action: rebuild
          path: ../sniffer
          ignore:
            - tmp/
            - vendor/
            - "*.log"

networks:
  sniffer-network:
    driver: bridge
  mungos-shared:
    name: mungos-shared-network
    external: false
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  clickhouse-sniffer-data:
    name: mungos_clickhouse_sniffer-data