version: '3.8'

services:
  postgres-sniffer:
    image: postgres:16-alpine
    container_name: mungos-postgres-sniffer
    environment:
      POSTGRES_DB: mungos_sniffer
      POSTGRES_USER: mungos
      POSTGRES_PASSWORD: mungos123
    volumes:
      - postgres-sniffer-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"  # 5434 на хосте
    networks:
      - sniffer-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mungos"]
      interval: 10s
      timeout: 5s
      retries: 5

  sniffer-app:
    build:
      context: ../sniffer
      dockerfile: Dockerfile
    container_name: mungos-sniffer-app
    depends_on:
      postgres-sniffer:
        condition: service_healthy
    environment:
      DB_HOST: postgres-sniffer
      DB_PORT: 5432
      DB_USER: mungos
      DB_PASS: mungos123
      DB_NAME: mungos_sniffer
    ports:
      - "8081:8080"  # порт Go приложения
    networks:
      - sniffer-network

networks:
  sniffer-network:
    driver: bridge

volumes:
  postgres-sniffer-data: