version: '3.8'
name: mungos-master

services:
  postgres-core:
    image: postgres:16-alpine
    container_name: mungos-postgres-core
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres-core-data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - core-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  core-app:
    build:
      context: ../core
      dockerfile: Dockerfile
    container_name: mungos-core
    depends_on:
      postgres-core:
        condition: service_healthy
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      TZ: ${TZ}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CORE_PORT: ${CORE_PORT}
      SNIFFER_GRPC_PORT: ${SNIFFER_GRPC_PORT}
      DEFAULT_MASTER_KEY: ${DEFAULT_MASTER_KEY}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${CORE_PORT}:7779"
    networks:
      - core-network
      - mungos-shared
    develop:
      watch:
        - action: rebuild
          path: ../core
          ignore:
          - target/   
          - .mvn/

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
      - API_URL=${API_URL}
      - SNIFFER_NAME=${SNIFFER_NAME}
      - SNIFFER_GRPC_PORT=${SNIFFER_GRPC_PORT}
    container_name: mungos-frontend
    restart: unless-stopped
    ports:
      - "${FRONT_PORT}:3000"
    networks:
      - core-network

  prometheus:
    image: prom/prometheus:latest
    container_name: mungos-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - core-network
      - mungos-shared
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

networks:
  core-network:
    driver: bridge
  mungos-shared:
    driver: bridge
    name: mungos-shared-network
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  postgres-core-data:
    name: mungos_postgres-core-data
  prometheus-data:
    name: mungos_prometheus-data