// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: proto/sniffer.proto

package snifferpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	PacketId      string                 `protobuf:"bytes,2,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadRequest) Reset() {
	*x = PayloadRequest{}
	mi := &file_proto_sniffer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadRequest) ProtoMessage() {}

func (x *PayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadRequest.ProtoReflect.Descriptor instead.
func (*PayloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{0}
}

func (x *PayloadRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *PayloadRequest) GetPacketId() string {
	if x != nil {
		return x.PacketId
	}
	return ""
}

type PayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadResponse) Reset() {
	*x = PayloadResponse{}
	mi := &file_proto_sniffer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadResponse) ProtoMessage() {}

func (x *PayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadResponse.ProtoReflect.Descriptor instead.
func (*PayloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{1}
}

func (x *PayloadResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TrafficFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Filter        *FilterExpression      `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficFilterRequest) Reset() {
	*x = TrafficFilterRequest{}
	mi := &file_proto_sniffer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficFilterRequest) ProtoMessage() {}

func (x *TrafficFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficFilterRequest.ProtoReflect.Descriptor instead.
func (*TrafficFilterRequest) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{2}
}

func (x *TrafficFilterRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *TrafficFilterRequest) GetFilter() *FilterExpression {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *TrafficFilterRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TrafficFilterRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FilterExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocols     []string               `protobuf:"bytes,1,rep,name=protocols,proto3" json:"protocols,omitempty"`                                                                     // ["TCP", "UDP", "HTTP"]
	Ports         []int32                `protobuf:"varint,2,rep,packed,name=ports,proto3" json:"ports,omitempty"`                                                                     // [80, 443, 53]
	Ips           []string               `protobuf:"bytes,3,rep,name=ips,proto3" json:"ips,omitempty"`                                                                                 // ["192.168.1.1", "10.0.0.1"]
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                                                   // с какого времени
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                                                         // по какое время
	TextSearch    string                 `protobuf:"bytes,6,opt,name=text_search,json=textSearch,proto3" json:"text_search,omitempty"`                                                 // поиск по содержимому
	Custom        map[string]string      `protobuf:"bytes,7,rep,name=custom,proto3" json:"custom,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // кастомные фильтры
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterExpression) Reset() {
	*x = FilterExpression{}
	mi := &file_proto_sniffer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterExpression) ProtoMessage() {}

func (x *FilterExpression) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterExpression.ProtoReflect.Descriptor instead.
func (*FilterExpression) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{3}
}

func (x *FilterExpression) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *FilterExpression) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *FilterExpression) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *FilterExpression) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *FilterExpression) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *FilterExpression) GetTextSearch() string {
	if x != nil {
		return x.TextSearch
	}
	return ""
}

func (x *FilterExpression) GetCustom() map[string]string {
	if x != nil {
		return x.Custom
	}
	return nil
}

type TrafficPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketId      string                 `protobuf:"bytes,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SrcPort       int32                  `protobuf:"varint,4,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort       int32                  `protobuf:"varint,5,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	SrcIp         string                 `protobuf:"bytes,6,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp         string                 `protobuf:"bytes,7,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	Length        int32                  `protobuf:"varint,8,opt,name=length,proto3" json:"length,omitempty"`
	Payload       []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,10,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Method        string                 `protobuf:"bytes,11,opt,name=method,proto3" json:"method,omitempty"`
	Uri           string                 `protobuf:"bytes,12,opt,name=uri,proto3" json:"uri,omitempty"`
	Status        int32                  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	DnsQuery      string                 `protobuf:"bytes,14,opt,name=dns_query,json=dnsQuery,proto3" json:"dns_query,omitempty"`
	DnsAnswer     string                 `protobuf:"bytes,15,opt,name=dns_answer,json=dnsAnswer,proto3" json:"dns_answer,omitempty"`
	Ttl           int32                  `protobuf:"varint,16,opt,name=ttl,proto3" json:"ttl,omitempty"`
	TcpFlags      string                 `protobuf:"bytes,17,opt,name=tcp_flags,json=tcpFlags,proto3" json:"tcp_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPacket) Reset() {
	*x = TrafficPacket{}
	mi := &file_proto_sniffer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPacket) ProtoMessage() {}

func (x *TrafficPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPacket.ProtoReflect.Descriptor instead.
func (*TrafficPacket) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{4}
}

func (x *TrafficPacket) GetPacketId() string {
	if x != nil {
		return x.PacketId
	}
	return ""
}

func (x *TrafficPacket) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TrafficPacket) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TrafficPacket) GetSrcPort() int32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *TrafficPacket) GetDstPort() int32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *TrafficPacket) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *TrafficPacket) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *TrafficPacket) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *TrafficPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TrafficPacket) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *TrafficPacket) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TrafficPacket) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *TrafficPacket) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TrafficPacket) GetDnsQuery() string {
	if x != nil {
		return x.DnsQuery
	}
	return ""
}

func (x *TrafficPacket) GetDnsAnswer() string {
	if x != nil {
		return x.DnsAnswer
	}
	return ""
}

func (x *TrafficPacket) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *TrafficPacket) GetTcpFlags() string {
	if x != nil {
		return x.TcpFlags
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterKey     string                 `protobuf:"bytes,1,opt,name=master_key,json=masterKey,proto3" json:"master_key,omitempty"`
	SnifferId     string                 `protobuf:"bytes,2,opt,name=sniffer_id,json=snifferId,proto3" json:"sniffer_id,omitempty"`
	SessionKey    string                 `protobuf:"bytes,3,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_sniffer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterRequest) GetMasterKey() string {
	if x != nil {
		return x.MasterKey
	}
	return ""
}

func (x *RegisterRequest) GetSnifferId() string {
	if x != nil {
		return x.SnifferId
	}
	return ""
}

func (x *RegisterRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type RegisterResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionKey        string                 `protobuf:"bytes,2,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ServerCertificate string                 `protobuf:"bytes,4,opt,name=server_certificate,json=serverCertificate,proto3" json:"server_certificate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_sniffer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetServerCertificate() string {
	if x != nil {
		return x.ServerCertificate
	}
	return ""
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_proto_sniffer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{7}
}

func (x *MetricsRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type MetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// === Основные счетчики трафика ===
	PacketsCount int64            `protobuf:"varint,1,opt,name=packets_count,json=packetsCount,proto3" json:"packets_count,omitempty"`                                                       // общее количество пакетов
	BytesTotal   int64            `protobuf:"varint,2,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`                                                             // общий трафик в байтах
	Protocols    map[string]int64 `protobuf:"bytes,3,rep,name=protocols,proto3" json:"protocols,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`       // статистика по протоколам (TCP, UDP, ICMP...)
	Applications map[string]int64 `protobuf:"bytes,4,rep,name=applications,proto3" json:"applications,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // статистика по приложениям (HTTP, DNS, HTTPS...)
	Error        string           `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                                                                          // ошибка, если есть
	// === Health метрики системы ===
	CpuUsage         float64 `protobuf:"fixed64,6,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`                          // загрузка CPU (0.0 - 100.0)
	MemoryBytes      int64   `protobuf:"varint,7,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`                  // используемая память в байтах
	MemoryTotalBytes int64   `protobuf:"varint,8,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"` // всего доступно памяти в байтах
	UptimeSeconds    int64   `protobuf:"varint,9,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`            // время работы сниффера в секундах
	PacketsDropped   int64   `protobuf:"varint,10,opt,name=packets_dropped,json=packetsDropped,proto3" json:"packets_dropped,omitempty"`        // сколько пакетов потеряно
	Version          string  `protobuf:"bytes,11,opt,name=version,proto3" json:"version,omitempty"`                                             // версия сниффера
	GoVersion        string  `protobuf:"bytes,12,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`                        // версия Go
	NumGoroutines    int32   `protobuf:"varint,13,opt,name=num_goroutines,json=numGoroutines,proto3" json:"num_goroutines,omitempty"`           // количество горутин
	Device           string  `protobuf:"bytes,14,opt,name=device,proto3" json:"device,omitempty"`                                               // сетевой интерфейс (eth0, lo...)
	PromiscMode      bool    `protobuf:"varint,15,opt,name=promisc_mode,json=promiscMode,proto3" json:"promisc_mode,omitempty"`                 // promiscuous mode включен?
	Filter           string  `protobuf:"bytes,16,opt,name=filter,proto3" json:"filter,omitempty"`                                               // BPF фильтр
	// === Временная аналитика ===
	PacketsPerSecond  int64   `protobuf:"varint,20,opt,name=packets_per_second,json=packetsPerSecond,proto3" json:"packets_per_second,omitempty"`    // текущая скорость пакетов (пакетов/сек)
	BytesPerSecond    float64 `protobuf:"fixed64,21,opt,name=bytes_per_second,json=bytesPerSecond,proto3" json:"bytes_per_second,omitempty"`         // текущая скорость трафика (байт/сек)
	PacketsLastMinute int64   `protobuf:"varint,22,opt,name=packets_last_minute,json=packetsLastMinute,proto3" json:"packets_last_minute,omitempty"` // пакеты за последнюю минуту
	BytesLastMinute   int64   `protobuf:"varint,23,opt,name=bytes_last_minute,json=bytesLastMinute,proto3" json:"bytes_last_minute,omitempty"`       // трафик за последнюю минуту (байт)
	// === TCP специфика ===
	TcpConnections     int64 `protobuf:"varint,30,opt,name=tcp_connections,json=tcpConnections,proto3" json:"tcp_connections,omitempty"`             // активные TCP соединения
	TcpSynPackets      int64 `protobuf:"varint,31,opt,name=tcp_syn_packets,json=tcpSynPackets,proto3" json:"tcp_syn_packets,omitempty"`              // SYN пакеты (новые соединения)
	TcpFinPackets      int64 `protobuf:"varint,32,opt,name=tcp_fin_packets,json=tcpFinPackets,proto3" json:"tcp_fin_packets,omitempty"`              // FIN пакеты (закрытые соединения)
	TcpRstPackets      int64 `protobuf:"varint,33,opt,name=tcp_rst_packets,json=tcpRstPackets,proto3" json:"tcp_rst_packets,omitempty"`              // RST пакеты (сброшенные/ошибочные)
	TcpRetransmissions int64 `protobuf:"varint,34,opt,name=tcp_retransmissions,json=tcpRetransmissions,proto3" json:"tcp_retransmissions,omitempty"` // ретрансмиссии (проблемы сети)
	// === Размеры пакетов ===
	AvgPacketSize          float64         `protobuf:"fixed64,40,opt,name=avg_packet_size,json=avgPacketSize,proto3" json:"avg_packet_size,omitempty"`                                                                                                      // средний размер пакета в байтах
	MinPacketSize          int64           `protobuf:"varint,41,opt,name=min_packet_size,json=minPacketSize,proto3" json:"min_packet_size,omitempty"`                                                                                                       // минимальный размер пакета
	MaxPacketSize          int64           `protobuf:"varint,42,opt,name=max_packet_size,json=maxPacketSize,proto3" json:"max_packet_size,omitempty"`                                                                                                       // максимальный размер пакета
	PacketSizeDistribution map[int32]int64 `protobuf:"bytes,43,rep,name=packet_size_distribution,json=packetSizeDistribution,proto3" json:"packet_size_distribution,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // распределение по размерам
	// === IP специфика ===
	Ipv4Packets       int64 `protobuf:"varint,50,opt,name=ipv4_packets,json=ipv4Packets,proto3" json:"ipv4_packets,omitempty"`                   // IPv4 трафик
	Ipv6Packets       int64 `protobuf:"varint,51,opt,name=ipv6_packets,json=ipv6Packets,proto3" json:"ipv6_packets,omitempty"`                   // IPv6 трафик
	FragmentedPackets int64 `protobuf:"varint,52,opt,name=fragmented_packets,json=fragmentedPackets,proto3" json:"fragmented_packets,omitempty"` // фрагментированные пакеты
	MalformedPackets  int64 `protobuf:"varint,53,opt,name=malformed_packets,json=malformedPackets,proto3" json:"malformed_packets,omitempty"`    // битые/ошибочные пакеты
	// === Топ портов ===
	TopSrcPorts map[int32]int64 `protobuf:"bytes,60,rep,name=top_src_ports,json=topSrcPorts,proto3" json:"top_src_ports,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // топ источников по портам (max 10)
	TopDstPorts map[int32]int64 `protobuf:"bytes,61,rep,name=top_dst_ports,json=topDstPorts,proto3" json:"top_dst_ports,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // топ назначений по портам (max 10)
	// === Топ IP адресов ===
	TopSrcIps map[string]int64 `protobuf:"bytes,70,rep,name=top_src_ips,json=topSrcIps,proto3" json:"top_src_ips,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // кто больше всего отправляет (max 10)
	TopDstIps map[string]int64 `protobuf:"bytes,71,rep,name=top_dst_ips,json=topDstIps,proto3" json:"top_dst_ips,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // кому больше всего отправляют (max 10)
	// === География (если будет реализовано) ===
	GeoCountries  map[string]int64 `protobuf:"bytes,80,rep,name=geo_countries,json=geoCountries,proto3" json:"geo_countries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // распределение по странам (ISO коды)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_sniffer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{8}
}

func (x *MetricsResponse) GetPacketsCount() int64 {
	if x != nil {
		return x.PacketsCount
	}
	return 0
}

func (x *MetricsResponse) GetBytesTotal() int64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

func (x *MetricsResponse) GetProtocols() map[string]int64 {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *MetricsResponse) GetApplications() map[string]int64 {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *MetricsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MetricsResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *MetricsResponse) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *MetricsResponse) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *MetricsResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *MetricsResponse) GetPacketsDropped() int64 {
	if x != nil {
		return x.PacketsDropped
	}
	return 0
}

func (x *MetricsResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MetricsResponse) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *MetricsResponse) GetNumGoroutines() int32 {
	if x != nil {
		return x.NumGoroutines
	}
	return 0
}

func (x *MetricsResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *MetricsResponse) GetPromiscMode() bool {
	if x != nil {
		return x.PromiscMode
	}
	return false
}

func (x *MetricsResponse) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *MetricsResponse) GetPacketsPerSecond() int64 {
	if x != nil {
		return x.PacketsPerSecond
	}
	return 0
}

func (x *MetricsResponse) GetBytesPerSecond() float64 {
	if x != nil {
		return x.BytesPerSecond
	}
	return 0
}

func (x *MetricsResponse) GetPacketsLastMinute() int64 {
	if x != nil {
		return x.PacketsLastMinute
	}
	return 0
}

func (x *MetricsResponse) GetBytesLastMinute() int64 {
	if x != nil {
		return x.BytesLastMinute
	}
	return 0
}

func (x *MetricsResponse) GetTcpConnections() int64 {
	if x != nil {
		return x.TcpConnections
	}
	return 0
}

func (x *MetricsResponse) GetTcpSynPackets() int64 {
	if x != nil {
		return x.TcpSynPackets
	}
	return 0
}

func (x *MetricsResponse) GetTcpFinPackets() int64 {
	if x != nil {
		return x.TcpFinPackets
	}
	return 0
}

func (x *MetricsResponse) GetTcpRstPackets() int64 {
	if x != nil {
		return x.TcpRstPackets
	}
	return 0
}

func (x *MetricsResponse) GetTcpRetransmissions() int64 {
	if x != nil {
		return x.TcpRetransmissions
	}
	return 0
}

func (x *MetricsResponse) GetAvgPacketSize() float64 {
	if x != nil {
		return x.AvgPacketSize
	}
	return 0
}

func (x *MetricsResponse) GetMinPacketSize() int64 {
	if x != nil {
		return x.MinPacketSize
	}
	return 0
}

func (x *MetricsResponse) GetMaxPacketSize() int64 {
	if x != nil {
		return x.MaxPacketSize
	}
	return 0
}

func (x *MetricsResponse) GetPacketSizeDistribution() map[int32]int64 {
	if x != nil {
		return x.PacketSizeDistribution
	}
	return nil
}

func (x *MetricsResponse) GetIpv4Packets() int64 {
	if x != nil {
		return x.Ipv4Packets
	}
	return 0
}

func (x *MetricsResponse) GetIpv6Packets() int64 {
	if x != nil {
		return x.Ipv6Packets
	}
	return 0
}

func (x *MetricsResponse) GetFragmentedPackets() int64 {
	if x != nil {
		return x.FragmentedPackets
	}
	return 0
}

func (x *MetricsResponse) GetMalformedPackets() int64 {
	if x != nil {
		return x.MalformedPackets
	}
	return 0
}

func (x *MetricsResponse) GetTopSrcPorts() map[int32]int64 {
	if x != nil {
		return x.TopSrcPorts
	}
	return nil
}

func (x *MetricsResponse) GetTopDstPorts() map[int32]int64 {
	if x != nil {
		return x.TopDstPorts
	}
	return nil
}

func (x *MetricsResponse) GetTopSrcIps() map[string]int64 {
	if x != nil {
		return x.TopSrcIps
	}
	return nil
}

func (x *MetricsResponse) GetTopDstIps() map[string]int64 {
	if x != nil {
		return x.TopDstIps
	}
	return nil
}

func (x *MetricsResponse) GetGeoCountries() map[string]int64 {
	if x != nil {
		return x.GeoCountries
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_sniffer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{9}
}

func (x *PingRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_sniffer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_sniffer_proto protoreflect.FileDescriptor

const file_proto_sniffer_proto_rawDesc = "" +
	"\n" +
	"\x13proto/sniffer.proto\x12\asniffer\"N\n" +
	"\x0ePayloadRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x12\x1b\n" +
	"\tpacket_id\x18\x02 \x01(\tR\bpacketId\"+\n" +
	"\x0fPayloadResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\x98\x01\n" +
	"\x14TrafficFilterRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x121\n" +
	"\x06filter\x18\x02 \x01(\v2\x19.sniffer.FilterExpressionR\x06filter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xad\x02\n" +
	"\x10FilterExpression\x12\x1c\n" +
	"\tprotocols\x18\x01 \x03(\tR\tprotocols\x12\x14\n" +
	"\x05ports\x18\x02 \x03(\x05R\x05ports\x12\x10\n" +
	"\x03ips\x18\x03 \x03(\tR\x03ips\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1f\n" +
	"\vtext_search\x18\x06 \x01(\tR\n" +
	"textSearch\x12=\n" +
	"\x06custom\x18\a \x03(\v2%.sniffer.FilterExpression.CustomEntryR\x06custom\x1a9\n" +
	"\vCustomEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x04\n" +
	"\rTrafficPacket\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\tR\bpacketId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x19\n" +
	"\bsrc_port\x18\x04 \x01(\x05R\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x05 \x01(\x05R\adstPort\x12\x15\n" +
	"\x06src_ip\x18\x06 \x01(\tR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\a \x01(\tR\x05dstIp\x12\x16\n" +
	"\x06length\x18\b \x01(\x05R\x06length\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\x12=\n" +
	"\aheaders\x18\n" +
	" \x03(\v2#.sniffer.TrafficPacket.HeadersEntryR\aheaders\x12\x16\n" +
	"\x06method\x18\v \x01(\tR\x06method\x12\x10\n" +
	"\x03uri\x18\f \x01(\tR\x03uri\x12\x16\n" +
	"\x06status\x18\r \x01(\x05R\x06status\x12\x1b\n" +
	"\tdns_query\x18\x0e \x01(\tR\bdnsQuery\x12\x1d\n" +
	"\n" +
	"dns_answer\x18\x0f \x01(\tR\tdnsAnswer\x12\x10\n" +
	"\x03ttl\x18\x10 \x01(\x05R\x03ttl\x12\x1b\n" +
	"\ttcp_flags\x18\x11 \x01(\tR\btcpFlags\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"master_key\x18\x01 \x01(\tR\tmasterKey\x12\x1d\n" +
	"\n" +
	"sniffer_id\x18\x02 \x01(\tR\tsnifferId\x12\x1f\n" +
	"\vsession_key\x18\x03 \x01(\tR\n" +
	"sessionKey\"\x96\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vsession_key\x18\x02 \x01(\tR\n" +
	"sessionKey\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12-\n" +
	"\x12server_certificate\x18\x04 \x01(\tR\x11serverCertificate\"1\n" +
	"\x0eMetricsRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\"\x8d\x12\n" +
	"\x0fMetricsResponse\x12#\n" +
	"\rpackets_count\x18\x01 \x01(\x03R\fpacketsCount\x12\x1f\n" +
	"\vbytes_total\x18\x02 \x01(\x03R\n" +
	"bytesTotal\x12E\n" +
	"\tprotocols\x18\x03 \x03(\v2'.sniffer.MetricsResponse.ProtocolsEntryR\tprotocols\x12N\n" +
	"\fapplications\x18\x04 \x03(\v2*.sniffer.MetricsResponse.ApplicationsEntryR\fapplications\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1b\n" +
	"\tcpu_usage\x18\x06 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_bytes\x18\a \x01(\x03R\vmemoryBytes\x12,\n" +
	"\x12memory_total_bytes\x18\b \x01(\x03R\x10memoryTotalBytes\x12%\n" +
	"\x0euptime_seconds\x18\t \x01(\x03R\ruptimeSeconds\x12'\n" +
	"\x0fpackets_dropped\x18\n" +
	" \x01(\x03R\x0epacketsDropped\x12\x18\n" +
	"\aversion\x18\v \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"go_version\x18\f \x01(\tR\tgoVersion\x12%\n" +
	"\x0enum_goroutines\x18\r \x01(\x05R\rnumGoroutines\x12\x16\n" +
	"\x06device\x18\x0e \x01(\tR\x06device\x12!\n" +
	"\fpromisc_mode\x18\x0f \x01(\bR\vpromiscMode\x12\x16\n" +
	"\x06filter\x18\x10 \x01(\tR\x06filter\x12,\n" +
	"\x12packets_per_second\x18\x14 \x01(\x03R\x10packetsPerSecond\x12(\n" +
	"\x10bytes_per_second\x18\x15 \x01(\x01R\x0ebytesPerSecond\x12.\n" +
	"\x13packets_last_minute\x18\x16 \x01(\x03R\x11packetsLastMinute\x12*\n" +
	"\x11bytes_last_minute\x18\x17 \x01(\x03R\x0fbytesLastMinute\x12'\n" +
	"\x0ftcp_connections\x18\x1e \x01(\x03R\x0etcpConnections\x12&\n" +
	"\x0ftcp_syn_packets\x18\x1f \x01(\x03R\rtcpSynPackets\x12&\n" +
	"\x0ftcp_fin_packets\x18  \x01(\x03R\rtcpFinPackets\x12&\n" +
	"\x0ftcp_rst_packets\x18! \x01(\x03R\rtcpRstPackets\x12/\n" +
	"\x13tcp_retransmissions\x18\" \x01(\x03R\x12tcpRetransmissions\x12&\n" +
	"\x0favg_packet_size\x18( \x01(\x01R\ravgPacketSize\x12&\n" +
	"\x0fmin_packet_size\x18) \x01(\x03R\rminPacketSize\x12&\n" +
	"\x0fmax_packet_size\x18* \x01(\x03R\rmaxPacketSize\x12n\n" +
	"\x18packet_size_distribution\x18+ \x03(\v24.sniffer.MetricsResponse.PacketSizeDistributionEntryR\x16packetSizeDistribution\x12!\n" +
	"\fipv4_packets\x182 \x01(\x03R\vipv4Packets\x12!\n" +
	"\fipv6_packets\x183 \x01(\x03R\vipv6Packets\x12-\n" +
	"\x12fragmented_packets\x184 \x01(\x03R\x11fragmentedPackets\x12+\n" +
	"\x11malformed_packets\x185 \x01(\x03R\x10malformedPackets\x12M\n" +
	"\rtop_src_ports\x18< \x03(\v2).sniffer.MetricsResponse.TopSrcPortsEntryR\vtopSrcPorts\x12M\n" +
	"\rtop_dst_ports\x18= \x03(\v2).sniffer.MetricsResponse.TopDstPortsEntryR\vtopDstPorts\x12G\n" +
	"\vtop_src_ips\x18F \x03(\v2'.sniffer.MetricsResponse.TopSrcIpsEntryR\ttopSrcIps\x12G\n" +
	"\vtop_dst_ips\x18G \x03(\v2'.sniffer.MetricsResponse.TopDstIpsEntryR\ttopDstIps\x12O\n" +
	"\rgeo_countries\x18P \x03(\v2*.sniffer.MetricsResponse.GeoCountriesEntryR\fgeoCountries\x1a<\n" +
	"\x0eProtocolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a?\n" +
	"\x11ApplicationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aI\n" +
	"\x1bPacketSizeDistributionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a>\n" +
	"\x10TopSrcPortsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a>\n" +
	"\x10TopDstPortsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a<\n" +
	"\x0eTopSrcIpsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a<\n" +
	"\x0eTopDstIpsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a?\n" +
	"\x11GeoCountriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"H\n" +
	"\vPingRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2\xdd\x02\n" +
	"\x0eSnifferService\x12?\n" +
	"\bRegister\x12\x18.sniffer.RegisterRequest\x1a\x19.sniffer.RegisterResponse\x12?\n" +
	"\n" +
	"GetMetrics\x12\x17.sniffer.MetricsRequest\x1a\x18.sniffer.MetricsResponse\x123\n" +
	"\x04Ping\x12\x14.sniffer.PingRequest\x1a\x15.sniffer.PingResponse\x12M\n" +
	"\x12GetFilteredTraffic\x12\x1d.sniffer.TrafficFilterRequest\x1a\x16.sniffer.TrafficPacket0\x01\x12E\n" +
	"\x10GetPacketPayload\x12\x17.sniffer.PayloadRequest\x1a\x18.sniffer.PayloadResponseB\x1dZ\x1b./core/grpc/proto;snifferpbb\x06proto3"

var (
	file_proto_sniffer_proto_rawDescOnce sync.Once
	file_proto_sniffer_proto_rawDescData []byte
)

func file_proto_sniffer_proto_rawDescGZIP() []byte {
	file_proto_sniffer_proto_rawDescOnce.Do(func() {
		file_proto_sniffer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sniffer_proto_rawDesc), len(file_proto_sniffer_proto_rawDesc)))
	})
	return file_proto_sniffer_proto_rawDescData
}

var file_proto_sniffer_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_sniffer_proto_goTypes = []any{
	(*PayloadRequest)(nil),       // 0: sniffer.PayloadRequest
	(*PayloadResponse)(nil),      // 1: sniffer.PayloadResponse
	(*TrafficFilterRequest)(nil), // 2: sniffer.TrafficFilterRequest
	(*FilterExpression)(nil),     // 3: sniffer.FilterExpression
	(*TrafficPacket)(nil),        // 4: sniffer.TrafficPacket
	(*RegisterRequest)(nil),      // 5: sniffer.RegisterRequest
	(*RegisterResponse)(nil),     // 6: sniffer.RegisterResponse
	(*MetricsRequest)(nil),       // 7: sniffer.MetricsRequest
	(*MetricsResponse)(nil),      // 8: sniffer.MetricsResponse
	(*PingRequest)(nil),          // 9: sniffer.PingRequest
	(*PingResponse)(nil),         // 10: sniffer.PingResponse
	nil,                          // 11: sniffer.FilterExpression.CustomEntry
	nil,                          // 12: sniffer.TrafficPacket.HeadersEntry
	nil,                          // 13: sniffer.MetricsResponse.ProtocolsEntry
	nil,                          // 14: sniffer.MetricsResponse.ApplicationsEntry
	nil,                          // 15: sniffer.MetricsResponse.PacketSizeDistributionEntry
	nil,                          // 16: sniffer.MetricsResponse.TopSrcPortsEntry
	nil,                          // 17: sniffer.MetricsResponse.TopDstPortsEntry
	nil,                          // 18: sniffer.MetricsResponse.TopSrcIpsEntry
	nil,                          // 19: sniffer.MetricsResponse.TopDstIpsEntry
	nil,                          // 20: sniffer.MetricsResponse.GeoCountriesEntry
}
var file_proto_sniffer_proto_depIdxs = []int32{
	3,  // 0: sniffer.TrafficFilterRequest.filter:type_name -> sniffer.FilterExpression
	11, // 1: sniffer.FilterExpression.custom:type_name -> sniffer.FilterExpression.CustomEntry
	12, // 2: sniffer.TrafficPacket.headers:type_name -> sniffer.TrafficPacket.HeadersEntry
	13, // 3: sniffer.MetricsResponse.protocols:type_name -> sniffer.MetricsResponse.ProtocolsEntry
	14, // 4: sniffer.MetricsResponse.applications:type_name -> sniffer.MetricsResponse.ApplicationsEntry
	15, // 5: sniffer.MetricsResponse.packet_size_distribution:type_name -> sniffer.MetricsResponse.PacketSizeDistributionEntry
	16, // 6: sniffer.MetricsResponse.top_src_ports:type_name -> sniffer.MetricsResponse.TopSrcPortsEntry
	17, // 7: sniffer.MetricsResponse.top_dst_ports:type_name -> sniffer.MetricsResponse.TopDstPortsEntry
	18, // 8: sniffer.MetricsResponse.top_src_ips:type_name -> sniffer.MetricsResponse.TopSrcIpsEntry
	19, // 9: sniffer.MetricsResponse.top_dst_ips:type_name -> sniffer.MetricsResponse.TopDstIpsEntry
	20, // 10: sniffer.MetricsResponse.geo_countries:type_name -> sniffer.MetricsResponse.GeoCountriesEntry
	5,  // 11: sniffer.SnifferService.Register:input_type -> sniffer.RegisterRequest
	7,  // 12: sniffer.SnifferService.GetMetrics:input_type -> sniffer.MetricsRequest
	9,  // 13: sniffer.SnifferService.Ping:input_type -> sniffer.PingRequest
	2,  // 14: sniffer.SnifferService.GetFilteredTraffic:input_type -> sniffer.TrafficFilterRequest
	0,  // 15: sniffer.SnifferService.GetPacketPayload:input_type -> sniffer.PayloadRequest
	6,  // 16: sniffer.SnifferService.Register:output_type -> sniffer.RegisterResponse
	8,  // 17: sniffer.SnifferService.GetMetrics:output_type -> sniffer.MetricsResponse
	10, // 18: sniffer.SnifferService.Ping:output_type -> sniffer.PingResponse
	4,  // 19: sniffer.SnifferService.GetFilteredTraffic:output_type -> sniffer.TrafficPacket
	1,  // 20: sniffer.SnifferService.GetPacketPayload:output_type -> sniffer.PayloadResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_sniffer_proto_init() }
func file_proto_sniffer_proto_init() {
	if File_proto_sniffer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sniffer_proto_rawDesc), len(file_proto_sniffer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sniffer_proto_goTypes,
		DependencyIndexes: file_proto_sniffer_proto_depIdxs,
		MessageInfos:      file_proto_sniffer_proto_msgTypes,
	}.Build()
	File_proto_sniffer_proto = out.File
	file_proto_sniffer_proto_goTypes = nil
	file_proto_sniffer_proto_depIdxs = nil
}
