// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: proto/sniffer.proto

package snifferpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateConnectionInsightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	PacketId      string                 `protobuf:"bytes,2,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	Ja4EntryId    string                 `protobuf:"bytes,3,opt,name=ja4_entry_id,json=ja4EntryId,proto3" json:"ja4_entry_id,omitempty"`
	SniEntryId    string                 `protobuf:"bytes,4,opt,name=sni_entry_id,json=sniEntryId,proto3" json:"sni_entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConnectionInsightRequest) Reset() {
	*x = UpdateConnectionInsightRequest{}
	mi := &file_proto_sniffer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConnectionInsightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConnectionInsightRequest) ProtoMessage() {}

func (x *UpdateConnectionInsightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConnectionInsightRequest.ProtoReflect.Descriptor instead.
func (*UpdateConnectionInsightRequest) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateConnectionInsightRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *UpdateConnectionInsightRequest) GetPacketId() string {
	if x != nil {
		return x.PacketId
	}
	return ""
}

func (x *UpdateConnectionInsightRequest) GetJa4EntryId() string {
	if x != nil {
		return x.Ja4EntryId
	}
	return ""
}

func (x *UpdateConnectionInsightRequest) GetSniEntryId() string {
	if x != nil {
		return x.SniEntryId
	}
	return ""
}

type UpdateConnectionInsightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConnectionInsightResponse) Reset() {
	*x = UpdateConnectionInsightResponse{}
	mi := &file_proto_sniffer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConnectionInsightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConnectionInsightResponse) ProtoMessage() {}

func (x *UpdateConnectionInsightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConnectionInsightResponse.ProtoReflect.Descriptor instead.
func (*UpdateConnectionInsightResponse) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateConnectionInsightResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateConnectionInsightResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConnectionInsightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	PacketId      string                 `protobuf:"bytes,2,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionInsightRequest) Reset() {
	*x = ConnectionInsightRequest{}
	mi := &file_proto_sniffer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInsightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInsightRequest) ProtoMessage() {}

func (x *ConnectionInsightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInsightRequest.ProtoReflect.Descriptor instead.
func (*ConnectionInsightRequest) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionInsightRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *ConnectionInsightRequest) GetPacketId() string {
	if x != nil {
		return x.PacketId
	}
	return ""
}

type ConnectionInsight struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LocalIp           string                 `protobuf:"bytes,1,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	LocalPorts        []uint32               `protobuf:"varint,2,rep,packed,name=local_ports,json=localPorts,proto3" json:"local_ports,omitempty"`
	RemoteIp          string                 `protobuf:"bytes,3,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	RemotePort        uint32                 `protobuf:"varint,4,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	TotalPackets      int64                  `protobuf:"varint,5,opt,name=total_packets,json=totalPackets,proto3" json:"total_packets,omitempty"`
	TotalBytes        int64                  `protobuf:"varint,6,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FirstPacketTime   int64                  `protobuf:"varint,7,opt,name=first_packet_time,json=firstPacketTime,proto3" json:"first_packet_time,omitempty"`
	LastPacketTime    int64                  `protobuf:"varint,8,opt,name=last_packet_time,json=lastPacketTime,proto3" json:"last_packet_time,omitempty"`
	SynCount          int64                  `protobuf:"varint,9,opt,name=syn_count,json=synCount,proto3" json:"syn_count,omitempty"`
	FinCount          int64                  `protobuf:"varint,10,opt,name=fin_count,json=finCount,proto3" json:"fin_count,omitempty"`
	RstCount          int64                  `protobuf:"varint,11,opt,name=rst_count,json=rstCount,proto3" json:"rst_count,omitempty"`
	IdentifiedPackets int64                  `protobuf:"varint,12,opt,name=identified_packets,json=identifiedPackets,proto3" json:"identified_packets,omitempty"`
	Ja4Candidates     []*JA4Candidate        `protobuf:"bytes,13,rep,name=ja4_candidates,json=ja4Candidates,proto3" json:"ja4_candidates,omitempty"`
	SniCandidates     []*SNICandidate        `protobuf:"bytes,14,rep,name=sni_candidates,json=sniCandidates,proto3" json:"sni_candidates,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConnectionInsight) Reset() {
	*x = ConnectionInsight{}
	mi := &file_proto_sniffer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInsight) ProtoMessage() {}

func (x *ConnectionInsight) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInsight.ProtoReflect.Descriptor instead.
func (*ConnectionInsight) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionInsight) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *ConnectionInsight) GetLocalPorts() []uint32 {
	if x != nil {
		return x.LocalPorts
	}
	return nil
}

func (x *ConnectionInsight) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *ConnectionInsight) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *ConnectionInsight) GetTotalPackets() int64 {
	if x != nil {
		return x.TotalPackets
	}
	return 0
}

func (x *ConnectionInsight) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *ConnectionInsight) GetFirstPacketTime() int64 {
	if x != nil {
		return x.FirstPacketTime
	}
	return 0
}

func (x *ConnectionInsight) GetLastPacketTime() int64 {
	if x != nil {
		return x.LastPacketTime
	}
	return 0
}

func (x *ConnectionInsight) GetSynCount() int64 {
	if x != nil {
		return x.SynCount
	}
	return 0
}

func (x *ConnectionInsight) GetFinCount() int64 {
	if x != nil {
		return x.FinCount
	}
	return 0
}

func (x *ConnectionInsight) GetRstCount() int64 {
	if x != nil {
		return x.RstCount
	}
	return 0
}

func (x *ConnectionInsight) GetIdentifiedPackets() int64 {
	if x != nil {
		return x.IdentifiedPackets
	}
	return 0
}

func (x *ConnectionInsight) GetJa4Candidates() []*JA4Candidate {
	if x != nil {
		return x.Ja4Candidates
	}
	return nil
}

func (x *ConnectionInsight) GetSniCandidates() []*SNICandidate {
	if x != nil {
		return x.SniCandidates
	}
	return nil
}

type JA4Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Application   string                 `protobuf:"bytes,3,opt,name=application,proto3" json:"application,omitempty"`
	Device        string                 `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Os            string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Count         int64                  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	Confidence    int32                  `protobuf:"varint,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Hop           int32                  `protobuf:"varint,8,opt,name=hop,proto3" json:"hop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JA4Candidate) Reset() {
	*x = JA4Candidate{}
	mi := &file_proto_sniffer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JA4Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JA4Candidate) ProtoMessage() {}

func (x *JA4Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JA4Candidate.ProtoReflect.Descriptor instead.
func (*JA4Candidate) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{4}
}

func (x *JA4Candidate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JA4Candidate) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *JA4Candidate) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *JA4Candidate) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *JA4Candidate) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *JA4Candidate) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *JA4Candidate) GetConfidence() int32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *JA4Candidate) GetHop() int32 {
	if x != nil {
		return x.Hop
	}
	return 0
}

type SNICandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sni           string                 `protobuf:"bytes,2,opt,name=sni,proto3" json:"sni,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Confidence    int32                  `protobuf:"varint,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Hop           int32                  `protobuf:"varint,6,opt,name=hop,proto3" json:"hop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNICandidate) Reset() {
	*x = SNICandidate{}
	mi := &file_proto_sniffer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNICandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNICandidate) ProtoMessage() {}

func (x *SNICandidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNICandidate.ProtoReflect.Descriptor instead.
func (*SNICandidate) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{5}
}

func (x *SNICandidate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SNICandidate) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *SNICandidate) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *SNICandidate) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SNICandidate) GetConfidence() int32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SNICandidate) GetHop() int32 {
	if x != nil {
		return x.Hop
	}
	return 0
}

type HashTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SniHash       uint64                 `protobuf:"varint,1,opt,name=sni_hash,json=sniHash,proto3" json:"sni_hash,omitempty"`
	Ja4Hash       uint64                 `protobuf:"varint,2,opt,name=ja4_hash,json=ja4Hash,proto3" json:"ja4_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashTable) Reset() {
	*x = HashTable{}
	mi := &file_proto_sniffer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashTable) ProtoMessage() {}

func (x *HashTable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashTable.ProtoReflect.Descriptor instead.
func (*HashTable) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{6}
}

func (x *HashTable) GetSniHash() uint64 {
	if x != nil {
		return x.SniHash
	}
	return 0
}

func (x *HashTable) GetJa4Hash() uint64 {
	if x != nil {
		return x.Ja4Hash
	}
	return 0
}

type SNIEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service         string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Sni             string                 `protobuf:"bytes,3,opt,name=sni,proto3" json:"sni,omitempty"`
	OccurrenceCount int32                  `protobuf:"varint,4,opt,name=occurrence_count,json=occurrenceCount,proto3" json:"occurrence_count,omitempty"`
	FirstSeen       int64                  `protobuf:"varint,5,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen        int64                  `protobuf:"varint,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	SessionKey      string                 `protobuf:"bytes,7,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SNIEntry) Reset() {
	*x = SNIEntry{}
	mi := &file_proto_sniffer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNIEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNIEntry) ProtoMessage() {}

func (x *SNIEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNIEntry.ProtoReflect.Descriptor instead.
func (*SNIEntry) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{7}
}

func (x *SNIEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SNIEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *SNIEntry) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *SNIEntry) GetOccurrenceCount() int32 {
	if x != nil {
		return x.OccurrenceCount
	}
	return 0
}

func (x *SNIEntry) GetFirstSeen() int64 {
	if x != nil {
		return x.FirstSeen
	}
	return 0
}

func (x *SNIEntry) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *SNIEntry) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type SNIEntryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SNIEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNIEntryList) Reset() {
	*x = SNIEntryList{}
	mi := &file_proto_sniffer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNIEntryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNIEntryList) ProtoMessage() {}

func (x *SNIEntryList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNIEntryList.ProtoReflect.Descriptor instead.
func (*SNIEntryList) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{8}
}

func (x *SNIEntryList) GetEntries() []*SNIEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SNIDataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	TotalSize     int32                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNIDataChunk) Reset() {
	*x = SNIDataChunk{}
	mi := &file_proto_sniffer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNIDataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNIDataChunk) ProtoMessage() {}

func (x *SNIDataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNIDataChunk.ProtoReflect.Descriptor instead.
func (*SNIDataChunk) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{9}
}

func (x *SNIDataChunk) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *SNIDataChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SNIDataChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *SNIDataChunk) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type SNIDataChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNIDataChunkRequest) Reset() {
	*x = SNIDataChunkRequest{}
	mi := &file_proto_sniffer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNIDataChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNIDataChunkRequest) ProtoMessage() {}

func (x *SNIDataChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNIDataChunkRequest.ProtoReflect.Descriptor instead.
func (*SNIDataChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{10}
}

func (x *SNIDataChunkRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type SNIDataChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNIDataChunkResponse) Reset() {
	*x = SNIDataChunkResponse{}
	mi := &file_proto_sniffer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNIDataChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNIDataChunkResponse) ProtoMessage() {}

func (x *SNIDataChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNIDataChunkResponse.ProtoReflect.Descriptor instead.
func (*SNIDataChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{11}
}

func (x *SNIDataChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SNIDataChunkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SNIDataChunkResponse) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

type JA4Entry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fingerprint      string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Application      string                 `protobuf:"bytes,3,opt,name=application,proto3" json:"application,omitempty"`
	Library          string                 `protobuf:"bytes,4,opt,name=library,proto3" json:"library,omitempty"`
	Device           string                 `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`
	Os               string                 `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	ObservationCount int32                  `protobuf:"varint,7,opt,name=observation_count,json=observationCount,proto3" json:"observation_count,omitempty"`
	Verified         bool                   `protobuf:"varint,8,opt,name=verified,proto3" json:"verified,omitempty"`
	FingerprintType  string                 `protobuf:"bytes,9,opt,name=fingerprint_type,json=fingerprintType,proto3" json:"fingerprint_type,omitempty"`
	SessionKey       string                 `protobuf:"bytes,10,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JA4Entry) Reset() {
	*x = JA4Entry{}
	mi := &file_proto_sniffer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JA4Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JA4Entry) ProtoMessage() {}

func (x *JA4Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JA4Entry.ProtoReflect.Descriptor instead.
func (*JA4Entry) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{12}
}

func (x *JA4Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JA4Entry) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *JA4Entry) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *JA4Entry) GetLibrary() string {
	if x != nil {
		return x.Library
	}
	return ""
}

func (x *JA4Entry) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *JA4Entry) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *JA4Entry) GetObservationCount() int32 {
	if x != nil {
		return x.ObservationCount
	}
	return 0
}

func (x *JA4Entry) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *JA4Entry) GetFingerprintType() string {
	if x != nil {
		return x.FingerprintType
	}
	return ""
}

func (x *JA4Entry) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *JA4Entry) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type JA4EntryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*JA4Entry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JA4EntryList) Reset() {
	*x = JA4EntryList{}
	mi := &file_proto_sniffer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JA4EntryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JA4EntryList) ProtoMessage() {}

func (x *JA4EntryList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JA4EntryList.ProtoReflect.Descriptor instead.
func (*JA4EntryList) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{13}
}

func (x *JA4EntryList) GetEntries() []*JA4Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Ja4DataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	TotalSize     int32                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ja4DataChunk) Reset() {
	*x = Ja4DataChunk{}
	mi := &file_proto_sniffer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ja4DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ja4DataChunk) ProtoMessage() {}

func (x *Ja4DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ja4DataChunk.ProtoReflect.Descriptor instead.
func (*Ja4DataChunk) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{14}
}

func (x *Ja4DataChunk) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *Ja4DataChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Ja4DataChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *Ja4DataChunk) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type Ja4DataChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ja4DataChunkRequest) Reset() {
	*x = Ja4DataChunkRequest{}
	mi := &file_proto_sniffer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ja4DataChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ja4DataChunkRequest) ProtoMessage() {}

func (x *Ja4DataChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ja4DataChunkRequest.ProtoReflect.Descriptor instead.
func (*Ja4DataChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{15}
}

func (x *Ja4DataChunkRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type Ja4DataChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ja4DataChunkResponse) Reset() {
	*x = Ja4DataChunkResponse{}
	mi := &file_proto_sniffer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ja4DataChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ja4DataChunkResponse) ProtoMessage() {}

func (x *Ja4DataChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ja4DataChunkResponse.ProtoReflect.Descriptor instead.
func (*Ja4DataChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{16}
}

func (x *Ja4DataChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ja4DataChunkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Ja4DataChunkResponse) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

type PayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	PacketId      string                 `protobuf:"bytes,2,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadRequest) Reset() {
	*x = PayloadRequest{}
	mi := &file_proto_sniffer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadRequest) ProtoMessage() {}

func (x *PayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadRequest.ProtoReflect.Descriptor instead.
func (*PayloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{17}
}

func (x *PayloadRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *PayloadRequest) GetPacketId() string {
	if x != nil {
		return x.PacketId
	}
	return ""
}

type PayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadResponse) Reset() {
	*x = PayloadResponse{}
	mi := &file_proto_sniffer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadResponse) ProtoMessage() {}

func (x *PayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadResponse.ProtoReflect.Descriptor instead.
func (*PayloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{18}
}

func (x *PayloadResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PackageFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Filter        *FilterExpression      `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageFilterRequest) Reset() {
	*x = PackageFilterRequest{}
	mi := &file_proto_sniffer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageFilterRequest) ProtoMessage() {}

func (x *PackageFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageFilterRequest.ProtoReflect.Descriptor instead.
func (*PackageFilterRequest) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{19}
}

func (x *PackageFilterRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *PackageFilterRequest) GetFilter() *FilterExpression {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *PackageFilterRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PackageFilterRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FilterExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocols     []string               `protobuf:"bytes,1,rep,name=protocols,proto3" json:"protocols,omitempty"`                                                                     // ["TCP", "UDP", "HTTP"]
	Ports         []int32                `protobuf:"varint,2,rep,packed,name=ports,proto3" json:"ports,omitempty"`                                                                     // [80, 443, 53]
	Ips           []string               `protobuf:"bytes,3,rep,name=ips,proto3" json:"ips,omitempty"`                                                                                 // ["192.168.1.1", "10.0.0.1"]
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                                                   // с какого времени
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                                                         // по какое время
	TextSearch    string                 `protobuf:"bytes,6,opt,name=text_search,json=textSearch,proto3" json:"text_search,omitempty"`                                                 // поиск по содержимому
	Custom        map[string]string      `protobuf:"bytes,7,rep,name=custom,proto3" json:"custom,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // кастомные фильтры
	UnknownOnly   bool                   `protobuf:"varint,8,opt,name=unknown_only,json=unknownOnly,proto3" json:"unknown_only,omitempty"`
	KnownOnly     bool                   `protobuf:"varint,9,opt,name=known_only,json=knownOnly,proto3" json:"known_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterExpression) Reset() {
	*x = FilterExpression{}
	mi := &file_proto_sniffer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterExpression) ProtoMessage() {}

func (x *FilterExpression) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterExpression.ProtoReflect.Descriptor instead.
func (*FilterExpression) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{20}
}

func (x *FilterExpression) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *FilterExpression) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *FilterExpression) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *FilterExpression) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *FilterExpression) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *FilterExpression) GetTextSearch() string {
	if x != nil {
		return x.TextSearch
	}
	return ""
}

func (x *FilterExpression) GetCustom() map[string]string {
	if x != nil {
		return x.Custom
	}
	return nil
}

func (x *FilterExpression) GetUnknownOnly() bool {
	if x != nil {
		return x.UnknownOnly
	}
	return false
}

func (x *FilterExpression) GetKnownOnly() bool {
	if x != nil {
		return x.KnownOnly
	}
	return false
}

type TrafficPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketId      string                 `protobuf:"bytes,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProtocolStack []string               `protobuf:"bytes,3,rep,name=protocol_stack,json=protocolStack,proto3" json:"protocol_stack,omitempty"`
	SrcPort       int32                  `protobuf:"varint,4,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort       int32                  `protobuf:"varint,5,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	SrcIp         string                 `protobuf:"bytes,6,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp         string                 `protobuf:"bytes,7,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	Length        int32                  `protobuf:"varint,8,opt,name=length,proto3" json:"length,omitempty"`
	Payload       []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,10,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Method        string                 `protobuf:"bytes,11,opt,name=method,proto3" json:"method,omitempty"`
	Uri           string                 `protobuf:"bytes,12,opt,name=uri,proto3" json:"uri,omitempty"`
	Status        int32                  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	DnsQuery      string                 `protobuf:"bytes,14,opt,name=dns_query,json=dnsQuery,proto3" json:"dns_query,omitempty"`
	DnsAnswer     string                 `protobuf:"bytes,15,opt,name=dns_answer,json=dnsAnswer,proto3" json:"dns_answer,omitempty"`
	Ttl           int32                  `protobuf:"varint,16,opt,name=ttl,proto3" json:"ttl,omitempty"`
	TcpFlags      string                 `protobuf:"bytes,17,opt,name=tcp_flags,json=tcpFlags,proto3" json:"tcp_flags,omitempty"`
	// MAC и Vendor (18-25)
	SrcMac    string `protobuf:"bytes,18,opt,name=src_mac,json=srcMac,proto3" json:"src_mac,omitempty"`
	DstMac    string `protobuf:"bytes,19,opt,name=dst_mac,json=dstMac,proto3" json:"dst_mac,omitempty"`
	SrcVendor string `protobuf:"bytes,20,opt,name=src_vendor,json=srcVendor,proto3" json:"src_vendor,omitempty"`
	DstVendor string `protobuf:"bytes,21,opt,name=dst_vendor,json=dstVendor,proto3" json:"dst_vendor,omitempty"`
	// JA4 fields (22-27)
	Ja4Raw         string `protobuf:"bytes,22,opt,name=ja4_raw,json=ja4Raw,proto3" json:"ja4_raw,omitempty"`
	Ja4Type        string `protobuf:"bytes,23,opt,name=ja4_type,json=ja4Type,proto3" json:"ja4_type,omitempty"`
	Ja4Application string `protobuf:"bytes,24,opt,name=ja4_application,json=ja4Application,proto3" json:"ja4_application,omitempty"`
	Ja4Device      string `protobuf:"bytes,25,opt,name=ja4_device,json=ja4Device,proto3" json:"ja4_device,omitempty"`
	Ja4Os          string `protobuf:"bytes,26,opt,name=ja4_os,json=ja4Os,proto3" json:"ja4_os,omitempty"`
	Ja4Verified    bool   `protobuf:"varint,27,opt,name=ja4_verified,json=ja4Verified,proto3" json:"ja4_verified,omitempty"`
	Ja4Confidence  int32  `protobuf:"varint,28,opt,name=ja4_confidence,json=ja4Confidence,proto3" json:"ja4_confidence,omitempty"`
	// SNI fields (28-29)
	Sni        string `protobuf:"bytes,29,opt,name=sni,proto3" json:"sni,omitempty"`
	SniService string `protobuf:"bytes,30,opt,name=sni_service,json=sniService,proto3" json:"sni_service,omitempty"`
	// IP Type fields (32-33)
	SrcIpType     string `protobuf:"bytes,31,opt,name=src_ip_type,json=srcIpType,proto3" json:"src_ip_type,omitempty"`
	DstIpType     string `protobuf:"bytes,32,opt,name=dst_ip_type,json=dstIpType,proto3" json:"dst_ip_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPacket) Reset() {
	*x = TrafficPacket{}
	mi := &file_proto_sniffer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPacket) ProtoMessage() {}

func (x *TrafficPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPacket.ProtoReflect.Descriptor instead.
func (*TrafficPacket) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{21}
}

func (x *TrafficPacket) GetPacketId() string {
	if x != nil {
		return x.PacketId
	}
	return ""
}

func (x *TrafficPacket) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TrafficPacket) GetProtocolStack() []string {
	if x != nil {
		return x.ProtocolStack
	}
	return nil
}

func (x *TrafficPacket) GetSrcPort() int32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *TrafficPacket) GetDstPort() int32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *TrafficPacket) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *TrafficPacket) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *TrafficPacket) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *TrafficPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TrafficPacket) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *TrafficPacket) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TrafficPacket) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *TrafficPacket) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TrafficPacket) GetDnsQuery() string {
	if x != nil {
		return x.DnsQuery
	}
	return ""
}

func (x *TrafficPacket) GetDnsAnswer() string {
	if x != nil {
		return x.DnsAnswer
	}
	return ""
}

func (x *TrafficPacket) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *TrafficPacket) GetTcpFlags() string {
	if x != nil {
		return x.TcpFlags
	}
	return ""
}

func (x *TrafficPacket) GetSrcMac() string {
	if x != nil {
		return x.SrcMac
	}
	return ""
}

func (x *TrafficPacket) GetDstMac() string {
	if x != nil {
		return x.DstMac
	}
	return ""
}

func (x *TrafficPacket) GetSrcVendor() string {
	if x != nil {
		return x.SrcVendor
	}
	return ""
}

func (x *TrafficPacket) GetDstVendor() string {
	if x != nil {
		return x.DstVendor
	}
	return ""
}

func (x *TrafficPacket) GetJa4Raw() string {
	if x != nil {
		return x.Ja4Raw
	}
	return ""
}

func (x *TrafficPacket) GetJa4Type() string {
	if x != nil {
		return x.Ja4Type
	}
	return ""
}

func (x *TrafficPacket) GetJa4Application() string {
	if x != nil {
		return x.Ja4Application
	}
	return ""
}

func (x *TrafficPacket) GetJa4Device() string {
	if x != nil {
		return x.Ja4Device
	}
	return ""
}

func (x *TrafficPacket) GetJa4Os() string {
	if x != nil {
		return x.Ja4Os
	}
	return ""
}

func (x *TrafficPacket) GetJa4Verified() bool {
	if x != nil {
		return x.Ja4Verified
	}
	return false
}

func (x *TrafficPacket) GetJa4Confidence() int32 {
	if x != nil {
		return x.Ja4Confidence
	}
	return 0
}

func (x *TrafficPacket) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *TrafficPacket) GetSniService() string {
	if x != nil {
		return x.SniService
	}
	return ""
}

func (x *TrafficPacket) GetSrcIpType() string {
	if x != nil {
		return x.SrcIpType
	}
	return ""
}

func (x *TrafficPacket) GetDstIpType() string {
	if x != nil {
		return x.DstIpType
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterKey     string                 `protobuf:"bytes,1,opt,name=master_key,json=masterKey,proto3" json:"master_key,omitempty"`
	SessionKey    string                 `protobuf:"bytes,2,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_sniffer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{22}
}

func (x *RegisterRequest) GetMasterKey() string {
	if x != nil {
		return x.MasterKey
	}
	return ""
}

func (x *RegisterRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type RegisterResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionKey        string                 `protobuf:"bytes,2,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ServerCertificate string                 `protobuf:"bytes,4,opt,name=server_certificate,json=serverCertificate,proto3" json:"server_certificate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_sniffer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{23}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetServerCertificate() string {
	if x != nil {
		return x.ServerCertificate
	}
	return ""
}

type SettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Filters       string                 `protobuf:"bytes,2,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingRequest) Reset() {
	*x = SettingRequest{}
	mi := &file_proto_sniffer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingRequest) ProtoMessage() {}

func (x *SettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingRequest.ProtoReflect.Descriptor instead.
func (*SettingRequest) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{24}
}

func (x *SettingRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *SettingRequest) GetFilters() string {
	if x != nil {
		return x.Filters
	}
	return ""
}

type SettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       string                 `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingResponse) Reset() {
	*x = SettingResponse{}
	mi := &file_proto_sniffer_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingResponse) ProtoMessage() {}

func (x *SettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingResponse.ProtoReflect.Descriptor instead.
func (*SettingResponse) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{25}
}

func (x *SettingResponse) GetFilters() string {
	if x != nil {
		return x.Filters
	}
	return ""
}

func (x *SettingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_proto_sniffer_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{26}
}

func (x *AuthRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type MetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Основные счетчики трафика
	PacketsCount   int64            `protobuf:"varint,1,opt,name=packets_count,json=packetsCount,proto3" json:"packets_count,omitempty"`
	BytesTotal     int64            `protobuf:"varint,2,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	Protocols      map[string]int64 `protobuf:"bytes,3,rep,name=protocols,proto3" json:"protocols,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	WellKnownPorts map[string]int64 `protobuf:"bytes,4,rep,name=well_known_ports,json=wellKnownPorts,proto3" json:"well_known_ports,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Error          string           `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// Временная аналитика
	PacketsPerSecond int64   `protobuf:"varint,6,opt,name=packets_per_second,json=packetsPerSecond,proto3" json:"packets_per_second,omitempty"`
	BytesPerSecond   float64 `protobuf:"fixed64,7,opt,name=bytes_per_second,json=bytesPerSecond,proto3" json:"bytes_per_second,omitempty"`
	// TCP специфика
	TcpConnections int64 `protobuf:"varint,8,opt,name=tcp_connections,json=tcpConnections,proto3" json:"tcp_connections,omitempty"`
	TcpSynPackets  int64 `protobuf:"varint,9,opt,name=tcp_syn_packets,json=tcpSynPackets,proto3" json:"tcp_syn_packets,omitempty"`
	TcpFinPackets  int64 `protobuf:"varint,10,opt,name=tcp_fin_packets,json=tcpFinPackets,proto3" json:"tcp_fin_packets,omitempty"`
	TcpRstPackets  int64 `protobuf:"varint,11,opt,name=tcp_rst_packets,json=tcpRstPackets,proto3" json:"tcp_rst_packets,omitempty"`
	// Топ сервисов (по именам)
	TopServices map[string]int64 `protobuf:"bytes,12,rep,name=top_services,json=topServices,proto3" json:"top_services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Топ приложений (по названиям)
	TopApplications map[string]int64 `protobuf:"bytes,13,rep,name=top_applications,json=topApplications,proto3" json:"top_applications,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Известные/неизвестные пакеты общие
	AllKnow   int64 `protobuf:"varint,14,opt,name=all_know,json=allKnow,proto3" json:"all_know,omitempty"`
	AllUnknow int64 `protobuf:"varint,15,opt,name=all_unknow,json=allUnknow,proto3" json:"all_unknow,omitempty"`
	// Известные/неизвестные пакеты за последние 5 секунд
	KnownPackets_5Sec        int64            `protobuf:"varint,16,opt,name=known_packets_5sec,json=knownPackets5sec,proto3" json:"known_packets_5sec,omitempty"`
	UnknownPackets_5Sec      int64            `protobuf:"varint,17,opt,name=unknown_packets_5sec,json=unknownPackets5sec,proto3" json:"unknown_packets_5sec,omitempty"`
	TopServicesByConnections map[string]int64 `protobuf:"bytes,18,rep,name=top_services_by_connections,json=topServicesByConnections,proto3" json:"top_services_by_connections,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_sniffer_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{27}
}

func (x *MetricsResponse) GetPacketsCount() int64 {
	if x != nil {
		return x.PacketsCount
	}
	return 0
}

func (x *MetricsResponse) GetBytesTotal() int64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

func (x *MetricsResponse) GetProtocols() map[string]int64 {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *MetricsResponse) GetWellKnownPorts() map[string]int64 {
	if x != nil {
		return x.WellKnownPorts
	}
	return nil
}

func (x *MetricsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MetricsResponse) GetPacketsPerSecond() int64 {
	if x != nil {
		return x.PacketsPerSecond
	}
	return 0
}

func (x *MetricsResponse) GetBytesPerSecond() float64 {
	if x != nil {
		return x.BytesPerSecond
	}
	return 0
}

func (x *MetricsResponse) GetTcpConnections() int64 {
	if x != nil {
		return x.TcpConnections
	}
	return 0
}

func (x *MetricsResponse) GetTcpSynPackets() int64 {
	if x != nil {
		return x.TcpSynPackets
	}
	return 0
}

func (x *MetricsResponse) GetTcpFinPackets() int64 {
	if x != nil {
		return x.TcpFinPackets
	}
	return 0
}

func (x *MetricsResponse) GetTcpRstPackets() int64 {
	if x != nil {
		return x.TcpRstPackets
	}
	return 0
}

func (x *MetricsResponse) GetTopServices() map[string]int64 {
	if x != nil {
		return x.TopServices
	}
	return nil
}

func (x *MetricsResponse) GetTopApplications() map[string]int64 {
	if x != nil {
		return x.TopApplications
	}
	return nil
}

func (x *MetricsResponse) GetAllKnow() int64 {
	if x != nil {
		return x.AllKnow
	}
	return 0
}

func (x *MetricsResponse) GetAllUnknow() int64 {
	if x != nil {
		return x.AllUnknow
	}
	return 0
}

func (x *MetricsResponse) GetKnownPackets_5Sec() int64 {
	if x != nil {
		return x.KnownPackets_5Sec
	}
	return 0
}

func (x *MetricsResponse) GetUnknownPackets_5Sec() int64 {
	if x != nil {
		return x.UnknownPackets_5Sec
	}
	return 0
}

func (x *MetricsResponse) GetTopServicesByConnections() map[string]int64 {
	if x != nil {
		return x.TopServicesByConnections
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_sniffer_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{28}
}

func (x *PingRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_sniffer_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sniffer_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_sniffer_proto_rawDescGZIP(), []int{29}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_sniffer_proto protoreflect.FileDescriptor

const file_proto_sniffer_proto_rawDesc = "" +
	"\n" +
	"\x13proto/sniffer.proto\x12\asniffer\"\xa2\x01\n" +
	"\x1eUpdateConnectionInsightRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x12\x1b\n" +
	"\tpacket_id\x18\x02 \x01(\tR\bpacketId\x12 \n" +
	"\fja4_entry_id\x18\x03 \x01(\tR\n" +
	"ja4EntryId\x12 \n" +
	"\fsni_entry_id\x18\x04 \x01(\tR\n" +
	"sniEntryId\"U\n" +
	"\x1fUpdateConnectionInsightResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"X\n" +
	"\x18ConnectionInsightRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x12\x1b\n" +
	"\tpacket_id\x18\x02 \x01(\tR\bpacketId\"\xab\x04\n" +
	"\x11ConnectionInsight\x12\x19\n" +
	"\blocal_ip\x18\x01 \x01(\tR\alocalIp\x12\x1f\n" +
	"\vlocal_ports\x18\x02 \x03(\rR\n" +
	"localPorts\x12\x1b\n" +
	"\tremote_ip\x18\x03 \x01(\tR\bremoteIp\x12\x1f\n" +
	"\vremote_port\x18\x04 \x01(\rR\n" +
	"remotePort\x12#\n" +
	"\rtotal_packets\x18\x05 \x01(\x03R\ftotalPackets\x12\x1f\n" +
	"\vtotal_bytes\x18\x06 \x01(\x03R\n" +
	"totalBytes\x12*\n" +
	"\x11first_packet_time\x18\a \x01(\x03R\x0ffirstPacketTime\x12(\n" +
	"\x10last_packet_time\x18\b \x01(\x03R\x0elastPacketTime\x12\x1b\n" +
	"\tsyn_count\x18\t \x01(\x03R\bsynCount\x12\x1b\n" +
	"\tfin_count\x18\n" +
	" \x01(\x03R\bfinCount\x12\x1b\n" +
	"\trst_count\x18\v \x01(\x03R\brstCount\x12-\n" +
	"\x12identified_packets\x18\f \x01(\x03R\x11identifiedPackets\x12<\n" +
	"\x0eja4_candidates\x18\r \x03(\v2\x15.sniffer.JA4CandidateR\rja4Candidates\x12<\n" +
	"\x0esni_candidates\x18\x0e \x03(\v2\x15.sniffer.SNICandidateR\rsniCandidates\"\xd2\x01\n" +
	"\fJA4Candidate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12 \n" +
	"\vapplication\x18\x03 \x01(\tR\vapplication\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x03R\x05count\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x05R\n" +
	"confidence\x12\x10\n" +
	"\x03hop\x18\b \x01(\x05R\x03hop\"\x92\x01\n" +
	"\fSNICandidate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03sni\x18\x02 \x01(\tR\x03sni\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x05R\n" +
	"confidence\x12\x10\n" +
	"\x03hop\x18\x06 \x01(\x05R\x03hop\"A\n" +
	"\tHashTable\x12\x19\n" +
	"\bsni_hash\x18\x01 \x01(\x04R\asniHash\x12\x19\n" +
	"\bja4_hash\x18\x02 \x01(\x04R\aja4Hash\"\xce\x01\n" +
	"\bSNIEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x10\n" +
	"\x03sni\x18\x03 \x01(\tR\x03sni\x12)\n" +
	"\x10occurrence_count\x18\x04 \x01(\x05R\x0foccurrenceCount\x12\x1d\n" +
	"\n" +
	"first_seen\x18\x05 \x01(\x03R\tfirstSeen\x12\x1b\n" +
	"\tlast_seen\x18\x06 \x01(\x03R\blastSeen\x12\x1f\n" +
	"\vsession_key\x18\a \x01(\tR\n" +
	"sessionKey\";\n" +
	"\fSNIEntryList\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.sniffer.SNIEntryR\aentries\"{\n" +
	"\fSNIDataChunk\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x05R\ttotalSize\"6\n" +
	"\x13SNIDataChunkRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\"m\n" +
	"\x14SNIDataChunkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\"\xd4\x02\n" +
	"\bJA4Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12 \n" +
	"\vapplication\x18\x03 \x01(\tR\vapplication\x12\x18\n" +
	"\alibrary\x18\x04 \x01(\tR\alibrary\x12\x16\n" +
	"\x06device\x18\x05 \x01(\tR\x06device\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12+\n" +
	"\x11observation_count\x18\a \x01(\x05R\x10observationCount\x12\x1a\n" +
	"\bverified\x18\b \x01(\bR\bverified\x12)\n" +
	"\x10fingerprint_type\x18\t \x01(\tR\x0ffingerprintType\x12\x1f\n" +
	"\vsession_key\x18\n" +
	" \x01(\tR\n" +
	"sessionKey\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\";\n" +
	"\fJA4EntryList\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.sniffer.JA4EntryR\aentries\"{\n" +
	"\fJa4DataChunk\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x05R\ttotalSize\"6\n" +
	"\x13Ja4DataChunkRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\"m\n" +
	"\x14Ja4DataChunkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\"N\n" +
	"\x0ePayloadRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x12\x1b\n" +
	"\tpacket_id\x18\x02 \x01(\tR\bpacketId\"+\n" +
	"\x0fPayloadResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\x98\x01\n" +
	"\x14PackageFilterRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x121\n" +
	"\x06filter\x18\x02 \x01(\v2\x19.sniffer.FilterExpressionR\x06filter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xef\x02\n" +
	"\x10FilterExpression\x12\x1c\n" +
	"\tprotocols\x18\x01 \x03(\tR\tprotocols\x12\x14\n" +
	"\x05ports\x18\x02 \x03(\x05R\x05ports\x12\x10\n" +
	"\x03ips\x18\x03 \x03(\tR\x03ips\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1f\n" +
	"\vtext_search\x18\x06 \x01(\tR\n" +
	"textSearch\x12=\n" +
	"\x06custom\x18\a \x03(\v2%.sniffer.FilterExpression.CustomEntryR\x06custom\x12!\n" +
	"\funknown_only\x18\b \x01(\bR\vunknownOnly\x12\x1d\n" +
	"\n" +
	"known_only\x18\t \x01(\bR\tknownOnly\x1a9\n" +
	"\vCustomEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\a\n" +
	"\rTrafficPacket\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\tR\bpacketId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0eprotocol_stack\x18\x03 \x03(\tR\rprotocolStack\x12\x19\n" +
	"\bsrc_port\x18\x04 \x01(\x05R\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x05 \x01(\x05R\adstPort\x12\x15\n" +
	"\x06src_ip\x18\x06 \x01(\tR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\a \x01(\tR\x05dstIp\x12\x16\n" +
	"\x06length\x18\b \x01(\x05R\x06length\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\x12=\n" +
	"\aheaders\x18\n" +
	" \x03(\v2#.sniffer.TrafficPacket.HeadersEntryR\aheaders\x12\x16\n" +
	"\x06method\x18\v \x01(\tR\x06method\x12\x10\n" +
	"\x03uri\x18\f \x01(\tR\x03uri\x12\x16\n" +
	"\x06status\x18\r \x01(\x05R\x06status\x12\x1b\n" +
	"\tdns_query\x18\x0e \x01(\tR\bdnsQuery\x12\x1d\n" +
	"\n" +
	"dns_answer\x18\x0f \x01(\tR\tdnsAnswer\x12\x10\n" +
	"\x03ttl\x18\x10 \x01(\x05R\x03ttl\x12\x1b\n" +
	"\ttcp_flags\x18\x11 \x01(\tR\btcpFlags\x12\x17\n" +
	"\asrc_mac\x18\x12 \x01(\tR\x06srcMac\x12\x17\n" +
	"\adst_mac\x18\x13 \x01(\tR\x06dstMac\x12\x1d\n" +
	"\n" +
	"src_vendor\x18\x14 \x01(\tR\tsrcVendor\x12\x1d\n" +
	"\n" +
	"dst_vendor\x18\x15 \x01(\tR\tdstVendor\x12\x17\n" +
	"\aja4_raw\x18\x16 \x01(\tR\x06ja4Raw\x12\x19\n" +
	"\bja4_type\x18\x17 \x01(\tR\aja4Type\x12'\n" +
	"\x0fja4_application\x18\x18 \x01(\tR\x0eja4Application\x12\x1d\n" +
	"\n" +
	"ja4_device\x18\x19 \x01(\tR\tja4Device\x12\x15\n" +
	"\x06ja4_os\x18\x1a \x01(\tR\x05ja4Os\x12!\n" +
	"\fja4_verified\x18\x1b \x01(\bR\vja4Verified\x12%\n" +
	"\x0eja4_confidence\x18\x1c \x01(\x05R\rja4Confidence\x12\x10\n" +
	"\x03sni\x18\x1d \x01(\tR\x03sni\x12\x1f\n" +
	"\vsni_service\x18\x1e \x01(\tR\n" +
	"sniService\x12\x1e\n" +
	"\vsrc_ip_type\x18\x1f \x01(\tR\tsrcIpType\x12\x1e\n" +
	"\vdst_ip_type\x18  \x01(\tR\tdstIpType\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"master_key\x18\x01 \x01(\tR\tmasterKey\x12\x1f\n" +
	"\vsession_key\x18\x02 \x01(\tR\n" +
	"sessionKey\"\x96\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vsession_key\x18\x02 \x01(\tR\n" +
	"sessionKey\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12-\n" +
	"\x12server_certificate\x18\x04 \x01(\tR\x11serverCertificate\"K\n" +
	"\x0eSettingRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x12\x18\n" +
	"\afilters\x18\x02 \x01(\tR\afilters\"I\n" +
	"\x0fSettingResponse\x12\x18\n" +
	"\afilters\x18\x01 \x01(\tR\afilters\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\".\n" +
	"\vAuthRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\"\x90\n" +
	"\n" +
	"\x0fMetricsResponse\x12#\n" +
	"\rpackets_count\x18\x01 \x01(\x03R\fpacketsCount\x12\x1f\n" +
	"\vbytes_total\x18\x02 \x01(\x03R\n" +
	"bytesTotal\x12E\n" +
	"\tprotocols\x18\x03 \x03(\v2'.sniffer.MetricsResponse.ProtocolsEntryR\tprotocols\x12V\n" +
	"\x10well_known_ports\x18\x04 \x03(\v2,.sniffer.MetricsResponse.WellKnownPortsEntryR\x0ewellKnownPorts\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12,\n" +
	"\x12packets_per_second\x18\x06 \x01(\x03R\x10packetsPerSecond\x12(\n" +
	"\x10bytes_per_second\x18\a \x01(\x01R\x0ebytesPerSecond\x12'\n" +
	"\x0ftcp_connections\x18\b \x01(\x03R\x0etcpConnections\x12&\n" +
	"\x0ftcp_syn_packets\x18\t \x01(\x03R\rtcpSynPackets\x12&\n" +
	"\x0ftcp_fin_packets\x18\n" +
	" \x01(\x03R\rtcpFinPackets\x12&\n" +
	"\x0ftcp_rst_packets\x18\v \x01(\x03R\rtcpRstPackets\x12L\n" +
	"\ftop_services\x18\f \x03(\v2).sniffer.MetricsResponse.TopServicesEntryR\vtopServices\x12X\n" +
	"\x10top_applications\x18\r \x03(\v2-.sniffer.MetricsResponse.TopApplicationsEntryR\x0ftopApplications\x12\x19\n" +
	"\ball_know\x18\x0e \x01(\x03R\aallKnow\x12\x1d\n" +
	"\n" +
	"all_unknow\x18\x0f \x01(\x03R\tallUnknow\x12,\n" +
	"\x12known_packets_5sec\x18\x10 \x01(\x03R\x10knownPackets5sec\x120\n" +
	"\x14unknown_packets_5sec\x18\x11 \x01(\x03R\x12unknownPackets5sec\x12u\n" +
	"\x1btop_services_by_connections\x18\x12 \x03(\v26.sniffer.MetricsResponse.TopServicesByConnectionsEntryR\x18topServicesByConnections\x1a<\n" +
	"\x0eProtocolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aA\n" +
	"\x13WellKnownPortsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a>\n" +
	"\x10TopServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aB\n" +
	"\x14TopApplicationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aK\n" +
	"\x1dTopServicesByConnectionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"H\n" +
	"\vPingRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2\x9c\t\n" +
	"\x0eSnifferService\x12?\n" +
	"\bRegister\x12\x18.sniffer.RegisterRequest\x1a\x19.sniffer.RegisterResponse\x12<\n" +
	"\n" +
	"GetMetrics\x12\x14.sniffer.AuthRequest\x1a\x18.sniffer.MetricsResponse\x123\n" +
	"\x04Ping\x12\x14.sniffer.PingRequest\x1a\x15.sniffer.PingResponse\x12M\n" +
	"\x12GetFilteredPackage\x12\x1d.sniffer.PackageFilterRequest\x1a\x16.sniffer.TrafficPacket0\x01\x12E\n" +
	"\x10GetPacketPayload\x12\x17.sniffer.PayloadRequest\x1a\x18.sniffer.PayloadResponse\x12@\n" +
	"\vGetSettings\x12\x17.sniffer.SettingRequest\x1a\x18.sniffer.SettingResponse\x12@\n" +
	"\vSetSettings\x12\x17.sniffer.SettingRequest\x1a\x18.sniffer.SettingResponse\x12L\n" +
	"\x13DownloadJA4Database\x12\x1c.sniffer.Ja4DataChunkRequest\x1a\x15.sniffer.Ja4DataChunk0\x01\x12K\n" +
	"\x11UploadJA4Database\x12\x15.sniffer.Ja4DataChunk\x1a\x1d.sniffer.Ja4DataChunkResponse(\x01\x12<\n" +
	"\x14UpdateOrSaveJa4Entry\x12\x11.sniffer.JA4Entry\x1a\x11.sniffer.JA4Entry\x12L\n" +
	"\x13DownloadSNIDatabase\x12\x1c.sniffer.SNIDataChunkRequest\x1a\x15.sniffer.SNIDataChunk0\x01\x12K\n" +
	"\x11UploadSNIDatabase\x12\x15.sniffer.SNIDataChunk\x1a\x1d.sniffer.SNIDataChunkResponse(\x01\x12<\n" +
	"\x14UpdateOrSaveSNIEntry\x12\x11.sniffer.SNIEntry\x1a\x11.sniffer.SNIEntry\x12E\n" +
	"\x19GetHashSNIandJa4HashTable\x12\x14.sniffer.AuthRequest\x1a\x12.sniffer.HashTable\x12U\n" +
	"\x14GetConnectionInsight\x12!.sniffer.ConnectionInsightRequest\x1a\x1a.sniffer.ConnectionInsight\x12l\n" +
	"\x17UpdateConnectionInsight\x12'.sniffer.UpdateConnectionInsightRequest\x1a(.sniffer.UpdateConnectionInsightResponseB\x1dZ\x1b./core/grpc/proto;snifferpbb\x06proto3"

var (
	file_proto_sniffer_proto_rawDescOnce sync.Once
	file_proto_sniffer_proto_rawDescData []byte
)

func file_proto_sniffer_proto_rawDescGZIP() []byte {
	file_proto_sniffer_proto_rawDescOnce.Do(func() {
		file_proto_sniffer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sniffer_proto_rawDesc), len(file_proto_sniffer_proto_rawDesc)))
	})
	return file_proto_sniffer_proto_rawDescData
}

var file_proto_sniffer_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_sniffer_proto_goTypes = []any{
	(*UpdateConnectionInsightRequest)(nil),  // 0: sniffer.UpdateConnectionInsightRequest
	(*UpdateConnectionInsightResponse)(nil), // 1: sniffer.UpdateConnectionInsightResponse
	(*ConnectionInsightRequest)(nil),        // 2: sniffer.ConnectionInsightRequest
	(*ConnectionInsight)(nil),               // 3: sniffer.ConnectionInsight
	(*JA4Candidate)(nil),                    // 4: sniffer.JA4Candidate
	(*SNICandidate)(nil),                    // 5: sniffer.SNICandidate
	(*HashTable)(nil),                       // 6: sniffer.HashTable
	(*SNIEntry)(nil),                        // 7: sniffer.SNIEntry
	(*SNIEntryList)(nil),                    // 8: sniffer.SNIEntryList
	(*SNIDataChunk)(nil),                    // 9: sniffer.SNIDataChunk
	(*SNIDataChunkRequest)(nil),             // 10: sniffer.SNIDataChunkRequest
	(*SNIDataChunkResponse)(nil),            // 11: sniffer.SNIDataChunkResponse
	(*JA4Entry)(nil),                        // 12: sniffer.JA4Entry
	(*JA4EntryList)(nil),                    // 13: sniffer.JA4EntryList
	(*Ja4DataChunk)(nil),                    // 14: sniffer.Ja4DataChunk
	(*Ja4DataChunkRequest)(nil),             // 15: sniffer.Ja4DataChunkRequest
	(*Ja4DataChunkResponse)(nil),            // 16: sniffer.Ja4DataChunkResponse
	(*PayloadRequest)(nil),                  // 17: sniffer.PayloadRequest
	(*PayloadResponse)(nil),                 // 18: sniffer.PayloadResponse
	(*PackageFilterRequest)(nil),            // 19: sniffer.PackageFilterRequest
	(*FilterExpression)(nil),                // 20: sniffer.FilterExpression
	(*TrafficPacket)(nil),                   // 21: sniffer.TrafficPacket
	(*RegisterRequest)(nil),                 // 22: sniffer.RegisterRequest
	(*RegisterResponse)(nil),                // 23: sniffer.RegisterResponse
	(*SettingRequest)(nil),                  // 24: sniffer.SettingRequest
	(*SettingResponse)(nil),                 // 25: sniffer.SettingResponse
	(*AuthRequest)(nil),                     // 26: sniffer.AuthRequest
	(*MetricsResponse)(nil),                 // 27: sniffer.MetricsResponse
	(*PingRequest)(nil),                     // 28: sniffer.PingRequest
	(*PingResponse)(nil),                    // 29: sniffer.PingResponse
	nil,                                     // 30: sniffer.FilterExpression.CustomEntry
	nil,                                     // 31: sniffer.TrafficPacket.HeadersEntry
	nil,                                     // 32: sniffer.MetricsResponse.ProtocolsEntry
	nil,                                     // 33: sniffer.MetricsResponse.WellKnownPortsEntry
	nil,                                     // 34: sniffer.MetricsResponse.TopServicesEntry
	nil,                                     // 35: sniffer.MetricsResponse.TopApplicationsEntry
	nil,                                     // 36: sniffer.MetricsResponse.TopServicesByConnectionsEntry
}
var file_proto_sniffer_proto_depIdxs = []int32{
	4,  // 0: sniffer.ConnectionInsight.ja4_candidates:type_name -> sniffer.JA4Candidate
	5,  // 1: sniffer.ConnectionInsight.sni_candidates:type_name -> sniffer.SNICandidate
	7,  // 2: sniffer.SNIEntryList.entries:type_name -> sniffer.SNIEntry
	12, // 3: sniffer.JA4EntryList.entries:type_name -> sniffer.JA4Entry
	20, // 4: sniffer.PackageFilterRequest.filter:type_name -> sniffer.FilterExpression
	30, // 5: sniffer.FilterExpression.custom:type_name -> sniffer.FilterExpression.CustomEntry
	31, // 6: sniffer.TrafficPacket.headers:type_name -> sniffer.TrafficPacket.HeadersEntry
	32, // 7: sniffer.MetricsResponse.protocols:type_name -> sniffer.MetricsResponse.ProtocolsEntry
	33, // 8: sniffer.MetricsResponse.well_known_ports:type_name -> sniffer.MetricsResponse.WellKnownPortsEntry
	34, // 9: sniffer.MetricsResponse.top_services:type_name -> sniffer.MetricsResponse.TopServicesEntry
	35, // 10: sniffer.MetricsResponse.top_applications:type_name -> sniffer.MetricsResponse.TopApplicationsEntry
	36, // 11: sniffer.MetricsResponse.top_services_by_connections:type_name -> sniffer.MetricsResponse.TopServicesByConnectionsEntry
	22, // 12: sniffer.SnifferService.Register:input_type -> sniffer.RegisterRequest
	26, // 13: sniffer.SnifferService.GetMetrics:input_type -> sniffer.AuthRequest
	28, // 14: sniffer.SnifferService.Ping:input_type -> sniffer.PingRequest
	19, // 15: sniffer.SnifferService.GetFilteredPackage:input_type -> sniffer.PackageFilterRequest
	17, // 16: sniffer.SnifferService.GetPacketPayload:input_type -> sniffer.PayloadRequest
	24, // 17: sniffer.SnifferService.GetSettings:input_type -> sniffer.SettingRequest
	24, // 18: sniffer.SnifferService.SetSettings:input_type -> sniffer.SettingRequest
	15, // 19: sniffer.SnifferService.DownloadJA4Database:input_type -> sniffer.Ja4DataChunkRequest
	14, // 20: sniffer.SnifferService.UploadJA4Database:input_type -> sniffer.Ja4DataChunk
	12, // 21: sniffer.SnifferService.UpdateOrSaveJa4Entry:input_type -> sniffer.JA4Entry
	10, // 22: sniffer.SnifferService.DownloadSNIDatabase:input_type -> sniffer.SNIDataChunkRequest
	9,  // 23: sniffer.SnifferService.UploadSNIDatabase:input_type -> sniffer.SNIDataChunk
	7,  // 24: sniffer.SnifferService.UpdateOrSaveSNIEntry:input_type -> sniffer.SNIEntry
	26, // 25: sniffer.SnifferService.GetHashSNIandJa4HashTable:input_type -> sniffer.AuthRequest
	2,  // 26: sniffer.SnifferService.GetConnectionInsight:input_type -> sniffer.ConnectionInsightRequest
	0,  // 27: sniffer.SnifferService.UpdateConnectionInsight:input_type -> sniffer.UpdateConnectionInsightRequest
	23, // 28: sniffer.SnifferService.Register:output_type -> sniffer.RegisterResponse
	27, // 29: sniffer.SnifferService.GetMetrics:output_type -> sniffer.MetricsResponse
	29, // 30: sniffer.SnifferService.Ping:output_type -> sniffer.PingResponse
	21, // 31: sniffer.SnifferService.GetFilteredPackage:output_type -> sniffer.TrafficPacket
	18, // 32: sniffer.SnifferService.GetPacketPayload:output_type -> sniffer.PayloadResponse
	25, // 33: sniffer.SnifferService.GetSettings:output_type -> sniffer.SettingResponse
	25, // 34: sniffer.SnifferService.SetSettings:output_type -> sniffer.SettingResponse
	14, // 35: sniffer.SnifferService.DownloadJA4Database:output_type -> sniffer.Ja4DataChunk
	16, // 36: sniffer.SnifferService.UploadJA4Database:output_type -> sniffer.Ja4DataChunkResponse
	12, // 37: sniffer.SnifferService.UpdateOrSaveJa4Entry:output_type -> sniffer.JA4Entry
	9,  // 38: sniffer.SnifferService.DownloadSNIDatabase:output_type -> sniffer.SNIDataChunk
	11, // 39: sniffer.SnifferService.UploadSNIDatabase:output_type -> sniffer.SNIDataChunkResponse
	7,  // 40: sniffer.SnifferService.UpdateOrSaveSNIEntry:output_type -> sniffer.SNIEntry
	6,  // 41: sniffer.SnifferService.GetHashSNIandJa4HashTable:output_type -> sniffer.HashTable
	3,  // 42: sniffer.SnifferService.GetConnectionInsight:output_type -> sniffer.ConnectionInsight
	1,  // 43: sniffer.SnifferService.UpdateConnectionInsight:output_type -> sniffer.UpdateConnectionInsightResponse
	28, // [28:44] is the sub-list for method output_type
	12, // [12:28] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_sniffer_proto_init() }
func file_proto_sniffer_proto_init() {
	if File_proto_sniffer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sniffer_proto_rawDesc), len(file_proto_sniffer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sniffer_proto_goTypes,
		DependencyIndexes: file_proto_sniffer_proto_depIdxs,
		MessageInfos:      file_proto_sniffer_proto_msgTypes,
	}.Build()
	File_proto_sniffer_proto = out.File
	file_proto_sniffer_proto_goTypes = nil
	file_proto_sniffer_proto_depIdxs = nil
}
